---
title: "CERF_2025"
author: "Forest Schenck"
date: "2025-10-28"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

#Packages
```{r}
library(tidyr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(glue) #for plot function code; plot title function
library(purrr) #for plot function code; map function
library(zoo) #approx nas from neighbors

#GAMs
library(mgcv)

#Maps
library(maps)
library(mapdata)
library(mapproj)
library(ggnewscale)
```

#Data upload EG 2024-2025
```{r}

d.flw.stage.WHOI <- read.csv("Data/whoi.eelgrass.flw.stage.data.csv")

d.flw.den.WHOI <- read.csv("Data/whoi.eelgrass.density.data.csv")

d.flw.stage.RI.SNEP <- read.csv("Data/RI.snep.eelgrass.flw.stage.data.master.csv")

d.flw.den.RI.SNEP <- read.csv("Data/RI.snep.eelgrass.density.data.master.csv")

d.flw.stage.MA.SNEP <- read.csv("Data/snep.eelgrass.flw.stage.data.csv")

d.flw.den.MA.SNEP <- read.csv("Data/snep.eelgrass.density.data.csv")

d.flw.den.MApart.SNEP <- read.csv("Data/snep.mapartners.eelgrass.density.data.csv")

d.flw.stage.MApart.SNEP <- read.csv("Data/snep.mapartners.eelgrass.flw.stage.data.csv")
```


#Data upload Hobos (temp/light) for sites with full 2025 data
```{r}
d.t.AQ.1 <- read.csv("Data/Hobo/AQ_21177827.csv")
d.t.AQ.3 <- read.csv("Data/Hobo/AQ_10625902.csv")
d.t.AQ.2 <- read.csv("Data/Hobo/AQ_21258480.csv")

d.t.CB.1 <- read.csv("Data/Hobo/CB_21258498.csv")
d.t.CB.2 <- read.csv("Data/Hobo/CB_21258495.csv")
d.t.CB.3 <- read.csv("Data/Hobo/CB_21258487.csv")

d.t.DC.1 <- read.csv("Data/Hobo/DC_21258490.csv")
d.t.DC.2 <- read.csv("Data/Hobo/DC_21258491.csv")
d.t.DC.3 <- read.csv("Data/Hobo/DC_21258483.csv")

d.t.SH.1 <- read.csv("Data/Hobo/SH_21177828.csv")
d.t.SH.2 <- read.csv("Data/Hobo/SH_21258490.csv")
d.t.SH.3 <- read.csv("Data/Hobo/SH_21982356.csv")

d.t.WB.1 <- read.csv("Data/Hobo/WB_21177828.csv")
d.t.WB.2 <- read.csv("Data/Hobo/WB_21258496.csv")
d.t.WB.3 <- read.csv("Data/Hobo/WB_22288916.csv")

d.t.CC.1 <- read.csv("Data/Hobo/CC_21982329.csv")
d.t.CC.2 <- read.csv("Data/Hobo/CC_21982356.csv")
d.t.CC.3 <- read.csv("Data/Hobo/CC_21982338.csv")

d.t.OB.1 <- read.csv("Data/Hobo/OB_21982331.csv")
d.t.OB.2 <- read.csv("Data/Hobo/OB_21982358.csv")
d.t.OB.3 <- read.csv("Data/Hobo/OB_21982330.csv")

d.t.WC.1 <- read.csv("Data/Hobo/WC_21982332.csv")
d.t.WC.2 <- read.csv("Data/Hobo/WC_21982360.csv")
d.t.WC.3 <- read.csv("Data/Hobo/WC_21982329.csv")

d.t.GB.1 <- read.csv("Data/Hobo/GB_21982334.csv")
d.t.GB.2 <- read.csv("Data/Hobo/GB_21982330.csv")
d.t.GB.3 <- read.csv("Data/Hobo/GB_21982334_2025.csv")

d.t.NK.1 <- read.csv("Data/Hobo/RI/NK_21982367.csv")
d.t.NK.2 <- read.csv("Data/Hobo/RI/NK_21982359.csv")

d.t.JB.1 <- read.csv("Data/Hobo/RI/JB_21982339_2025.csv")
d.t.JB.2 <- read.csv("Data/Hobo/RI/JB_22329183.csv")

d.t.CL.1 <- read.csv("Data/Hobo/RI/CL_21982347.csv")

```

#Data Carpentry Hobos
##AQ
```{r}

d.t.AQ.1.water <- d.t.AQ.1 %>%
  mutate(site.id = "AQ") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-05-07 10:15") %>%
  filter(date.time <= "2024-09-30 10:45")

d.t.AQ.2.water <- d.t.AQ.2 %>%
  mutate(site.id = "AQ") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-09-30 11:00") %>%
  filter(date.time <= "2025-05-08 11:00")

d.t.AQ.3.water <- d.t.AQ.3 %>%
  mutate(site.id = "AQ") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 11:15") %>%
  filter(date.time <= "2025-09-24 10:15")

d.t.AQ.water <- bind_rows(d.t.AQ.1.water, d.t.AQ.2.water, d.t.AQ.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.AQ.water)


ggplot(data = d.t.AQ.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))
  
d.t.AQ.daily.range <- d.t.AQ.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(site.id, date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.AQ.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.AQ.GDD <- d.t.AQ.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.AQ.GDD <- d.t.AQ.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")
  
ggplot(data = d.t.AQ.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##CB
```{r}
d.t.CB.1.water <- d.t.CB.1 %>%
  mutate(site.id = "CB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-05-07 13:30") %>%
  filter(date.time <= "2024-09-30 12:30")

d.t.CB.2.water <- d.t.CB.2 %>%
  mutate(site.id = "CB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-09-30 12:45") %>%
  filter(date.time <= "2025-05-08 15:00")

d.t.CB.3.water <- d.t.CB.3 %>%
  mutate(site.id = "CB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 15:15") %>%
  filter(date.time <= "2025-09-15 9:15")

d.t.CB.water <- bind_rows(d.t.CB.1.water, d.t.CB.2.water, d.t.CB.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.CB.water)


ggplot(data = d.t.CB.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))


d.t.CB.daily.range <- d.t.CB.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(site.id, date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.CB.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.CB.GDD <- d.t.CB.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.CB.GDD <- d.t.CB.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")
  
ggplot(data = d.t.CB.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()
```

##DC
```{r}
d.t.DC.1.water <- d.t.DC.1 %>%
  mutate(site.id = "DC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-05-07 14:00") %>%
  filter(date.time <= "2024-09-30 13:00")

d.t.DC.2.water <- d.t.DC.2 %>%
  mutate(site.id = "DC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-09-30 13:15") %>%
  filter(date.time <= "2025-05-08 14:00")

d.t.DC.3.water <- d.t.DC.3 %>%
  mutate(site.id = "DC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 14:15") %>%
  filter(date.time <= "2025-10-10 11:30")

d.t.DC.water <- bind_rows(d.t.DC.1.water, d.t.DC.2.water, d.t.DC.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.DC.water)


ggplot(data = d.t.DC.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

d.t.DC.daily.range <- d.t.DC.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.DC.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.DC.GDD <- d.t.DC.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.DC.GDD <- d.t.DC.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")
  
ggplot(data = d.t.DC.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()
```

##SH*
```{r}
d.t.SH.1.water <- d.t.SH.1 %>%
  mutate(site.id = "SH") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-05-15 10:45") %>%
  filter(date.time <= "2024-10-08 9:00")

d.t.SH.2.water <- d.t.SH.2 %>%
  mutate(site.id = "SH") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-10-08 9:15") %>%
  filter(date.time <= "2025-06-04 11:15")

d.t.SH.3.water <- d.t.SH.3 %>%
  mutate(site.id = "SH") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-06-04 11:30") %>%
  filter(date.time <= "2025-09-04 14:45")

d.t.SH.water <- bind_rows(d.t.SH.1.water, d.t.SH.2.water, d.t.SH.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.SH.water)


ggplot(data = d.t.SH.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

d.t.SH.daily.range <- d.t.SH.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

#Exclude +/- 2 hrs low tides </= -1 MLLW at Dux station

ggplot(data = d.t.SH.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.SH.GDD <- d.t.SH.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.SH.GDD <- d.t.SH.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")
  
ggplot(data = d.t.SH.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##WB
```{r}
d.t.WB.1.water <- d.t.WB.1 %>%
  mutate(site.id = "WB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-10-22 12:45") %>%
  filter(date.time <= "2025-05-08 11:45")

d.t.WB.2.water <- d.t.WB.2 %>%
  mutate(site.id = "WB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 12:00") %>%
  filter(date.time <= "2025-07-15 10:45")

d.t.WB.3.water <- d.t.WB.3 %>%
  mutate(site.id = "WB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-07-15 11:00") %>%
  filter(date.time <= "2025-10-22 11:00")

d.t.WB.water <- bind_rows(d.t.WB.1.water, d.t.WB.2.water, d.t.WB.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.WB.water)


ggplot(data = d.t.WB.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

d.t.WB.daily.range <- d.t.WB.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.WB.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.WB.GDD <- d.t.WB.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.WB.GDD <- d.t.WB.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")
  
ggplot(data = d.t.WB.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##CC
```{r}
d.t.CC.1.water <- d.t.CC.1 %>%
  mutate(site.id = "CC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-04-16 9:45") %>%
  filter(date.time <= "2024-11-20 8:15")

str(d.t.CC.1.water)

d.t.CC.2.water <- d.t.CC.2 %>%
  mutate(site.id = "CC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-11-20 8:30") %>%
  filter(date.time <= "2025-05-08 11:45")

d.t.CC.3.water <- d.t.CC.3 %>%
  mutate(site.id = "CC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 12:00") %>%
  filter(date.time <= "2025-8-20 11:15")

d.t.CC.water <- bind_rows(d.t.CC.1.water, d.t.CC.2.water, d.t.CC.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.CC.water)


ggplot(data = d.t.CC.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

d.t.CC.daily.range <- d.t.CC.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.CC.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.CC.GDD <- d.t.CC.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.CC.GDD <- d.t.CC.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.CC.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##OB
```{r}
d.t.OB.1.water <- d.t.OB.1 %>%
  mutate(site.id = "OB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-04-16 13:00") %>%
  filter(date.time <= "2024-11-20 10:45")

d.t.OB.2.water <- d.t.OB.2 %>%
  mutate(site.id = "OB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-11-20 11:00") %>%
  filter(date.time <= "2025-05-08 12:45")

d.t.OB.3.water <- d.t.OB.3 %>%
  mutate(site.id = "OB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-08 13:00") %>%
  filter(date.time <= "2025-8-26 17:30")

d.t.OB.water <- bind_rows(d.t.OB.1.water, d.t.OB.2.water, d.t.OB.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.OB.water)


ggplot(data = d.t.OB.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

d.t.OB.daily.range <- d.t.OB.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.OB.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.OB.GDD <- d.t.OB.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.OB.GDD <- d.t.OB.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.OB.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##WC*
```{r}
d.t.WC.1.water <- d.t.WC.1 %>%
  mutate(site.id = "WC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-04-17 10:45") %>%
  filter(date.time <= "2024-11-20 12:00")

d.t.WC.2.water <- d.t.WC.2 %>%
  mutate(site.id = "WC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-11-20 12:15") %>%
  filter(date.time <= "2025-05-01 15:45")

d.t.WC.3.water <- d.t.WC.3 %>%
  mutate(site.id = "WC") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-01 16:00") %>%
  filter(date.time <= "2025-08-06 15:00")

d.t.WC.water <- bind_rows(d.t.WC.1.water, d.t.WC.2.water, d.t.WC.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.WC.water)


ggplot(data = d.t.WC.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))


d.t.WC.daily.range <- d.t.WC.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

#Exclude +/- 2 hrs low tides </= -0.25 MLLW at Monument Beach station
#Also exclude data with values < 0 C
#This data set tricky because hard to parse natural water temp variation from logger going dry.

ggplot(data = d.t.WC.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.WC.GDD <- d.t.WC.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.WC.GDD <- d.t.WC.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.WC.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()
```

##GB
```{r}
d.t.GB.1.water <- d.t.GB.1 %>%
  mutate(site.id = "GB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-04-17 12:30") %>%
  filter(date.time <= "2024-11-20 15:15")

d.t.GB.2.water <- d.t.GB.2 %>%
  mutate(site.id = "GB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-11-20 15:19") %>%
  filter(date.time <= "2025-05-01 17:49")

d.t.GB.3.water <- d.t.GB.3 %>%
  mutate(site.id = "GB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-05-01 18:15") %>%
  filter(date.time <= "2025-08-21 15:00")

d.t.GB.water <- bind_rows(d.t.GB.1.water, d.t.GB.2.water, d.t.GB.3.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.GB.water)


ggplot(data = d.t.GB.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))


d.t.GB.daily.range <- d.t.GB.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

#Anomalous low tide 2/18 2025 - exclude data from times tide < -1 ft MLLW , see noaa chart woods hole

start.time <- ymd_hm("2025-02-18 06:00", tz ="America/New_York")
end.time <- ymd_hm("2025-02-18 16:00" , tz ="America/New_York")
interval_to_exclude <-interval(start.time, end.time)

d.t.GB.water <- d.t.GB.water %>%
  filter(!(date.time %within% interval_to_exclude))

str(d.t.GB.water)

ggplot(data = d.t.GB.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.GB.GDD <- d.t.GB.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.GB.GDD <- d.t.GB.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.GB.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##NK*
```{r}
d.t.NK.1.water <- d.t.NK.1 %>%
  mutate(site.id = "NK") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-05-20 13:24") %>%
  filter(date.time <= "2024-09-11 10:09")


d.t.NK.2.water <- d.t.NK.2 %>%
  mutate(site.id = "NK") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-1-29 15:30") %>%
  filter(date.time <= "2025-07-22 14:45")

d.t.NK.water <- bind_rows(d.t.NK.1.water, d.t.NK.2.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.NK.water)


ggplot(data = d.t.NK.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))


d.t.NK.daily.range <- d.t.NK.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

#Some high negatives and positive anomalies need to be resolved

ggplot(data = d.t.NK.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-5,30))

d.t.NK.GDD <- d.t.NK.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.NK.GDD <- d.t.NK.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.NK.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##JB*
```{r}
d.t.JB.1.water <- d.t.JB.1 %>%
  mutate(site.id = "JB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-01-29 13:12") %>%
  filter(date.time <= "2025-06-18 9:12")


d.t.JB.2.water <- d.t.JB.2 %>%
  mutate(site.id = "JB") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = date.time - hours(1)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2025-6-18 09:30") %>%
  filter(date.time <= "2025-08-12 10:30")

d.t.JB.water <- bind_rows(d.t.JB.1.water, d.t.JB.2.water) %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.JB.water)


ggplot(data = d.t.JB.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))


d.t.JB.daily.range <- d.t.JB.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T)

ggplot(data = d.t.JB.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

#Need to fix range anomalies with NOAA tides

d.t.JB.GDD <- d.t.JB.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.JB.GDD <- d.t.JB.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.JB.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()

```

##CL*
```{r}
d.t.CL.1.water <- d.t.CL.1 %>%
  mutate(site.id = "CL") %>%
  mutate(date.time = mdy_hm(date.time)) %>%
  mutate(date.time = force_tz(date.time, "EST")) %>%
  mutate(date.time = with_tz(date.time, "America/New_York")) %>%
  filter(date.time >= "2024-12-10 9:15") %>%
  filter(date.time <= "2025-08-05 10:15")


d.t.CL.water <- d.t.CL.1.water %>%
  mutate(j = as.POSIXlt(date.time)$yday + 1)

str(d.t.CL.water)


ggplot(data = d.t.CL.water, aes(x = date.time, y = temp.C)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))


d.t.CL.daily.range <- d.t.CL.water %>%
  mutate(date = as_date(date.time)) %>%
  group_by(date) %>%
  summarize(min.T = min(temp.C), max.T = max(temp.C), median.T = median(temp.C)) %>%
  mutate(delta.T = max.T - min.T) %>%
  mutate(median.T = na.approx(median.T))

ggplot(data = d.t.CL.daily.range, aes(x = date, y = median.T)) +
  geom_line() +
  coord_cartesian(y = c(-1,28))

#Need to fix anomalies with NOAA tides

d.t.CL.GDD <- d.t.CL.daily.range %>%
  filter(date >= "2025-01-29") %>%
  mutate(GDD.2 = median.T-2) %>%
  mutate(across(GDD.2, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.2 = cumsum(GDD.2)) %>%
  mutate(GDD.4 = median.T-4) %>%
  mutate(across(GDD.4, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.4 = cumsum(GDD.4)) %>%
  mutate(GDD.6 = median.T-6) %>%
  mutate(across(GDD.6, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.6 = cumsum(GDD.6)) %>%
  mutate(GDD.8 = median.T-8) %>%
  mutate(across(GDD.8, ~ ifelse(. < 0, 0, .))) %>%
  mutate(GDD.8 = cumsum(GDD.8))

d.t.CL.GDD <- d.t.CL.GDD %>%
  pivot_longer(cols = c("GDD.2", "GDD.4", "GDD.6", "GDD.8"), names_to = "Tbase", values_to = "GDD")

ggplot(data = d.t.CL.GDD, aes(x = date, y = GDD, group = Tbase)) +
  geom_line()
```

##Merging data

#Data Carpentry Seeds per Flw
```{r}
str(d.flw.stage.WHOI)

d.flw.stage.RI.SNEP <- as.data.frame(d.flw.stage.RI.SNEP) %>%
  mutate(spathe.stage.0 = as.integer(spathe.stage.0),
         site.id = if_else(is.na(site.id) == T, "NR", site.id))
str(d.flw.stage.RI.SNEP)

d.flw.stage.MA.SNEP <- as.data.frame(d.flw.stage.MA.SNEP) %>%
  mutate(no.seeds = as.numeric(no.seeds))
str(d.flw.stage.MA.SNEP)

d.flw.stage.MApart.SNEP <- as.data.frame(d.flw.stage.MApart.SNEP)
str(d.flw.stage.MApart.SNEP)


d.flw.stage <- dplyr::bind_rows(d.flw.stage.WHOI, d.flw.stage.RI.SNEP, d.flw.stage.MA.SNEP, d.flw.stage.MApart.SNEP)

str(d.flw.stage)

d.seed.per.flw <- d.flw.stage %>%
  mutate(date.collected = mdy(date.collected)) %>%
  rowwise() %>%
  mutate(no.seeds.total = sum(no.seeds, no.ovules.w.stigma, na.rm = T)) %>%
  group_by(town, site.id, date.collected, shoot.no) %>%
  summarise(no.seeds.total = sum(no.seeds.total, na.rm = T)) %>%
  mutate(j = as.POSIXlt(date.collected)$yday + 1) %>% #add 1 for leap year
  filter(is.na(shoot.no) == FALSE) %>%
  group_by(date.collected, site.id) %>%
  summarise(mean.seeds.per.flw = mean(no.seeds.total))

d.seed.per.flw = as.data.frame(d.seed.per.flw)


str(d.seed.per.flw)

```
